substitutions:
  device_name: p1mini
  device_password: !secret ota_password
  device_api_key: !secret ha_api_encryption_key

esphome:
  name: ${device_name}

esp32:
  board: esp32-gateway

# Enable logging
logger:
  level: INFO              # Set to DEBUG if you are having issues!
  baud_rate: 0             # disable logging over uart

# Enable Home Assistant API
api:
  encryption:
    key: "${device_api_key}"

ota:
  platform: esphome # Remove this line to run on ESPHome versions earlier than 2022.6.0
  password: "${device_password}"

web_server:
  port: 80
  ota: false
#  auth:
#    username: admin
#    password: "${device_password}"

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  manual_ip:
    static_ip: 192.168.0.25
    gateway: 192.168.0.1
    subnet: 255.255.255.0

external_components:
  - source: components

one_wire:
  - platform: gpio
    pin: GPIO32

switch:
  # - platform: gpio
  #   id: p1_rts             # Not needed if the RTS signal is not connected to a GPIO
  #   pin:
  #     number: D2
  # - platform: gpio
  #   id: status_led
  #   pin:
  #     number: D4
  #     inverted: true
  - platform: gpio
    id: status_led
    pin:
      number: 13
      inverted: true
  - platform: gpio
    name: "Floor heating actuator garage"
    id: heating_garage
    pin:
      mcp23xxx: mcp23008_hub
      number: 0
      mode:
        output: True
      inverted: False

binary_sensor:
  - platform: gpio
    id: secondary_p1_rts # Currently not used, but make sure D0 is configured as input in case it is connected.
    pin:
      number: 35
      # mode: INPUT_PULLDOWN
      inverted: false

uart:
  id: my_uart
  # tx_pin:
  #   number: TX
  #   inverted: true
  #   mode: OUTPUT_OPEN_DRAIN
  rx_pin:
    number: 34
    inverted: true         # Set to false if inverting in hardware
    # mode: INPUT_PULLUP     # Set to INPUT if inverting in hardware
  baud_rate: 115200
  rx_buffer_size: 512      # Probably not needed, but it is good to have some margin.

i2c:
  sda: 16
  scl: 14
  scan: true
  id: bus_a

mcp23008:
  - id: 'mcp23008_hub'
    i2c_id: bus_a
    address: 0x20

climate:
  - platform: thermostat
    name: "Thermostat Garage"
    sensor: temperature_garage
    visual:
      min_temperature: 5 °C
    preset:
      - name: home
        default_target_temperature_low: 8 °C
        mode: heat
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    heat_deadband: 0.2
    heat_overrun: 0.2
    heat_action:
      - switch.turn_on: heating_garage
    idle_action:
      - switch.turn_off: heating_garage

p1_mini:
  id: p1_mini_1
  uart_id: my_uart
  minimum_period: 0s       # Should be 0 (zero) if the RTS signal is not used.
  buffer_size: 3072        # Needs to be large enough to hold one entire update from the meter.
  secondary_p1: false
  # on_ready_to_receive:
  #   then:
      # - switch.turn_on: p1_rts
      # - switch.turn_on: status_led
  # on_update_received:
  #   then:
      # - switch.turn_off: p1_rts
      # - switch.turn_off: status_led
  # on_communication_error:
  #   then:
  #     - switch.turn_off: p1_rts
  #     - switch.turn_off: status_led

sensor:
  - platform: dallas_temp
    address: 0x2703168660f3ff28
    name: "Garage temperatur"
    id: temperature_garage
    filters:
    - median:
        window_size: 7
        send_every: 5
        send_first_at: 3

  - platform: dallas_temp
    address: 0x840416900fe2ff28
    name: "Garage heat loop in"
    id: garage_heat_loop_in
    filters:
    - median:
        window_size: 7
        send_every: 5
        send_first_at: 3

  - platform: dallas_temp
    address: 0xa5051688087eff28
    name: "Garage heat loop out"
    id: garage_heat_loop_out
    filters:
    - median:
        window_size: 7
        send_every: 5
        send_first_at: 3


  - platform: p1_mini
    obis_code: "1.8.0"
    name: "Cumulative Active Import"
    unit_of_measurement: kWh
    accuracy_decimals: 3
    state_class: "total_increasing"
    device_class: "energy"
  - platform: p1_mini
    obis_code: "2.8.0"
    name: "Cumulative Active Export"
    unit_of_measurement: kWh
    accuracy_decimals: 3
    state_class: "total_increasing"
    device_class: "energy"
  - platform: p1_mini
    obis_code: "3.8.0"
    name: "Cumulative Reactive Import"
    unit_of_measurement: kvarh
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "4.8.0"
    name: "Cumulative Reactive Export"
    unit_of_measurement: kvarh
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "1.7.0"
    name: "Momentary Active Import"
    unit_of_measurement: kW
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "2.7.0"
    name: "Momentary Active Export"
    unit_of_measurement: kW
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "3.7.0"
    name: "Momentary Reactive Import"
    unit_of_measurement: kvar
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "4.7.0"
    name: "Momentary Reactive Export"
    unit_of_measurement: kvar
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "21.7.0"
    name: "Momentary Active Import Phase 1"
    unit_of_measurement: kW
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "22.7.0"
    name: "Momentary Active Export Phase 1"
    unit_of_measurement: kW
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "41.7.0"
    name: "Momentary Active Import Phase 2"
    unit_of_measurement: kW
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "42.7.0"
    name: "Momentary Active Export Phase 2"
    unit_of_measurement: kW
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "61.7.0"
    name: "Momentary Active Import Phase 3"
    unit_of_measurement: kW
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "62.7.0"
    name: "Momentary Active Export Phase 3"
    unit_of_measurement: kW
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "23.7.0"
    name: "Momentary Reactive Import Phase 1"
    unit_of_measurement: kvar
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "24.7.0"
    name: "Momentary Reactive Export Phase 1"
    unit_of_measurement: kvar
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "43.7.0"
    name: "Momentary Reactive Import Phase 2"
    unit_of_measurement: kvar
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "44.7.0"
    name: "Momentary Reactive Export Phase 2"
    unit_of_measurement: kvar
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "63.7.0"
    name: "Momentary Reactive Import Phase 3"
    unit_of_measurement: kvar
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "64.7.0"
    name: "Momentary Reactive Export Phase 3"
    unit_of_measurement: kvar
    accuracy_decimals: 3
  - platform: p1_mini
    obis_code: "32.7.0"
    name: "Voltage Phase 1"
    unit_of_measurement: V
    accuracy_decimals: 1
  - platform: p1_mini
    obis_code: "52.7.0"
    name: "Voltage Phase 2"
    unit_of_measurement: V
    accuracy_decimals: 1
  - platform: p1_mini
    obis_code: "72.7.0"
    name: "Voltage Phase 3"
    unit_of_measurement: V
    accuracy_decimals: 1
  - platform: p1_mini
    obis_code: "31.7.0"
    name: "Current Phase 1"
    unit_of_measurement: A
    accuracy_decimals: 1
  - platform: p1_mini
    obis_code: "51.7.0"
    name: "Current Phase 2"
    unit_of_measurement: A
    accuracy_decimals: 1
  - platform: p1_mini
    obis_code: "71.7.0"
    name: "Current Phase 3"
    unit_of_measurement: A
    accuracy_decimals: 1
